development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: hacker_school_dev
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: hacker_school_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: hacker_school_production
  pool: 5
  password:

